/*
 * Qualified Name as per http://www.w3.org/TR/xml-names11/#ns-qualnames for XML 1.1
*/

[0]     start                     ::= QName

[1]     QName                     ::= PrefixedName | UnprefixedName
[2]     PrefixedName              ::= Prefix ':' LocalPart
[3]     UnprefixedName            ::= LocalPart
[4]     Prefix                    ::= NCName
[5]     LocalPart                 ::= NCName
[6]     NCName                    ::= NCNameStartChar NCNameChar*	/* An XML Name, minus the ":" */
[7]     NCNameChar                ::= NameCharWithoutColon
[8]     NCNameStartChar           ::= NameStartCharWithoutColon
[9]     NameCharWithoutColon      ::= NameStartCharWithoutColon | "-" | "." | [0-9] | #xB7 | [#x0300-#x036F] | [#x203F-#x2040]
[10]    NameStartCharWithoutColon ::= [A-Z] | "_" | [a-z] | [#xC0-#xD6] | [#xD8-#xF6] | [#xF8-#x2FF] | [#x370-#x37D] | [#x37F-#x1FFF] | [#x200C-#x200D] | [#x2070-#x218F] | [#x2C00-#x2FEF] | [#x3001-#xD7FF] | [#xF900-#xFDCF] | [#xFDF0-#xFFFD] | [#x10000-#xEFFFF]
