#ifndef MARPAXML_API_DOM_CDATASECTION_H
#define MARPAXML_API_DOM_CDATASECTION_H

#include "marpaXml/DOM/Text.h"

SUBCLASS(CDATASection, Text)
  VTABLE(CDATASection, Text)
METHODS
END_CLASS

#endif /* MARPAXML_API_DOM_CDATASECTION_H */
